/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leap_years;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        LeapYear leapYear = new LeapYear();
        System.out.println(leapYear.check(2000));
        System.out.println(leapYear.check(1970));
        System.out.println(leapYear.check(1900));
        System.out.println(leapYear.check(1988));
        System.out.println(leapYear.check(1500));
        System.out.println(leapYear.checkRange(1500, 1520));
    }
}