/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leap_years;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        LeapYear leapYear2000 = new LeapYear(2000);
        System.out.println(leapYear2000.check());
        LeapYear leapYear1970 = new LeapYear(1970);
        System.out.println(leapYear1970.check());
        LeapYear leapYear1900 = new LeapYear(1900);
        System.out.println(leapYear1900.check());
        LeapYear leapYear1988 = new LeapYear(1988);
        System.out.println(leapYear1988.check());
        LeapYear leapYear1500 = new LeapYear(1500);
        System.out.println(leapYear1500.check());
    }
}